### ISSUE TITLE
cannot run client/test

### ISSUE THREAD

**Issue by MasseGuillaume** [d6y/wootjs#5]
I'm working on #3. I just want to let you know that with the current code in the repo sbt client/test fails

`sbt -Dsbt.log.noformat=true client/test | xclip -i`

```
[info] Loading project definition from /home/gui/wootjs/project
[info] Set current project to woot (in build file:/home/gui/wootjs/)
[error] Referring to non-existent class ju_concurrent_Executors$
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent method jl_Thread.setContextClassLoader__jl_ClassLoader__V
[error]   called from Lorg_scalacheck_Test$$anonfun$1$$anonfun$apply$1.apply__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$1$$anonfun$apply$1.apply__O
[error]   called from Lorg_scalacheck_Gen$.nonEmptyListOf__F0__Lorg_scalacheck_Gen
[error]   called from Lwoot_NonEmptyStringGenerator$.nonEmptyStringGen$lzycompute__p1__Lorg_scalacheck_Gen
[error]   called from Lwoot_NonEmptyStringGenerator$.nonEmptyStringGen__Lorg_scalacheck_Gen
[error]   called from Lwoot_NonEmptyStringGenerator$.arbitraryNonEmptyString$lzycompute__p1__Lorg_scalacheck_Arbitrary
[error]   called from Lwoot_NonEmptyStringGenerator$.arbitraryNonEmptyString__Lorg_scalacheck_Arbitrary
[error]   called from Lwoot_WootModelSpec$.init___
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   Lorg_scalacheck_Test$$anonfun$1$$anonfun$apply$1
[error]   Lorg_scalacheck_Gen$
[error]     (already seen, not repeating call stack)
[error]   Lwoot_NonEmptyStringGenerator$
[error] Referring to non-existent method ju_concurrent_Executors$.newFixedThreadPool__I__ju_concurrent_ExecutorService
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent class s_concurrent_forkjoin_ForkJoinTask
[error]   called from s_concurrent_impl_ExecutionContextImpl.execute__jl_Runnable__V
[error]   called from s_concurrent_impl_ExecutionContextImpl.execute__jl_Runnable__V
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error] Referring to non-existent class s_concurrent_forkjoin_ForkJoinWorkerThread
[error]   called from s_concurrent_impl_ExecutionContextImpl.execute__jl_Runnable__V
[error]   called from s_concurrent_impl_ExecutionContextImpl.execute__jl_Runnable__V
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error] Referring to non-existent class s_concurrent_forkjoin_ForkJoinPool
[error]   called from s_concurrent_impl_ExecutionContextImpl.execute__jl_Runnable__V
[error]   called from s_concurrent_impl_ExecutionContextImpl.execute__jl_Runnable__V
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error] Referring to non-existent method s_concurrent_impl_ExecutionContextImpl$AdaptedForkJoinTask.fork__s_concurrent_forkjoin_ForkJoinTask
[error]   called from s_concurrent_impl_ExecutionContextImpl.execute__jl_Runnable__V
[error]   called from s_concurrent_impl_ExecutionContextImpl.execute__jl_Runnable__V
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error] Referring to non-existent class s_concurrent_forkjoin_ForkJoinPool
[error]   called from s_concurrent_impl_ExecutionContextImpl.createExecutorService__ju_concurrent_ExecutorService
[error]   called from s_concurrent_impl_ExecutionContextImpl.init___ju_concurrent_Executor__F1
[error]   called from s_concurrent_impl_ExecutionContextImpl$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_impl_ExecutionContextImpl
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_ExecutionContextExecutor
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__s_concurrent_ExecutionContextExecutor
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error]   s_concurrent_impl_ExecutionContextImpl$
[error]   s_concurrent_ExecutionContext$
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent method s_concurrent_forkjoin_ForkJoinPool.execute__s_concurrent_forkjoin_ForkJoinTask__V
[error]   called from s_concurrent_impl_ExecutionContextImpl.execute__jl_Runnable__V
[error]   called from s_concurrent_impl_ExecutionContextImpl.execute__jl_Runnable__V
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error] Referring to non-existent class ju_concurrent_LinkedBlockingQueue
[error]   called from s_concurrent_impl_ExecutionContextImpl.createExecutorService__ju_concurrent_ExecutorService
[error]   called from s_concurrent_impl_ExecutionContextImpl.init___ju_concurrent_Executor__F1
[error]   called from s_concurrent_impl_ExecutionContextImpl$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_impl_ExecutionContextImpl
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_ExecutionContextExecutor
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__s_concurrent_ExecutionContextExecutor
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error]   s_concurrent_impl_ExecutionContextImpl$
[error]   s_concurrent_ExecutionContext$
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent class ju_concurrent_ThreadPoolExecutor
[error]   called from s_concurrent_impl_ExecutionContextImpl.createExecutorService__ju_concurrent_ExecutorService
[error]   called from s_concurrent_impl_ExecutionContextImpl.init___ju_concurrent_Executor__F1
[error]   called from s_concurrent_impl_ExecutionContextImpl$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_impl_ExecutionContextImpl
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_ExecutionContextExecutor
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__s_concurrent_ExecutionContextExecutor
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error]   s_concurrent_impl_ExecutionContextImpl$
[error]   s_concurrent_ExecutionContext$
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent method ju_concurrent_ThreadPoolExecutor.allowCoreThreadTimeOut__Z__V
[error]   called from s_concurrent_impl_ExecutionContextImpl.createExecutorService__ju_concurrent_ExecutorService
[error]   called from s_concurrent_impl_ExecutionContextImpl.init___ju_concurrent_Executor__F1
[error]   called from s_concurrent_impl_ExecutionContextImpl$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_impl_ExecutionContextImpl
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_ExecutionContextExecutor
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__s_concurrent_ExecutionContextExecutor
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error]   s_concurrent_impl_ExecutionContextImpl$
[error]   s_concurrent_ExecutionContext$
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent method jl_System$.getProperty__T__T__T
[error]   called from s_concurrent_impl_ExecutionContextImpl.getInt$1__p1__T__T__I
[error]   called from s_concurrent_impl_ExecutionContextImpl.createExecutorService__ju_concurrent_ExecutorService
[error]   called from s_concurrent_impl_ExecutionContextImpl.init___ju_concurrent_Executor__F1
[error]   called from s_concurrent_impl_ExecutionContextImpl$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_impl_ExecutionContextImpl
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_ExecutionContextExecutor
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__s_concurrent_ExecutionContextExecutor
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error]   s_concurrent_impl_ExecutionContextImpl$
[error]   s_concurrent_ExecutionContext$
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent method ju_concurrent_ThreadPoolExecutor.init___I__I__J__ju_concurrent_TimeUnit__ju_concurrent_BlockingQueue__ju_concurrent_ThreadFactory
[error]   called from s_concurrent_impl_ExecutionContextImpl.createExecutorService__ju_concurrent_ExecutorService
[error]   called from s_concurrent_impl_ExecutionContextImpl.init___ju_concurrent_Executor__F1
[error]   called from s_concurrent_impl_ExecutionContextImpl$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_impl_ExecutionContextImpl
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_ExecutionContextExecutor
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__s_concurrent_ExecutionContextExecutor
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error]   s_concurrent_impl_ExecutionContextImpl$
[error]   s_concurrent_ExecutionContext$
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent method s_concurrent_forkjoin_ForkJoinPool.init___I__s_concurrent_forkjoin_ForkJoinPool$ForkJoinWorkerThreadFactory__jl_Thread$UncaughtExceptionHandler__Z
[error]   called from s_concurrent_impl_ExecutionContextImpl.createExecutorService__ju_concurrent_ExecutorService
[error]   called from s_concurrent_impl_ExecutionContextImpl.init___ju_concurrent_Executor__F1
[error]   called from s_concurrent_impl_ExecutionContextImpl$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_impl_ExecutionContextImpl
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__F1__s_concurrent_ExecutionContextExecutor
[error]   called from s_concurrent_ExecutionContext$.fromExecutor__ju_concurrent_Executor__s_concurrent_ExecutionContextExecutor
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_ExecutionContextImpl
[error]   s_concurrent_impl_ExecutionContextImpl$
[error]   s_concurrent_ExecutionContext$
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent method s_concurrent_impl_Promise$CompletionLatch.releaseShared__I__Z
[error]   called from s_concurrent_impl_Promise$CompletionLatch.apply__s_util_Try__V
[error]   called from s_concurrent_impl_Promise$CompletionLatch.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_Promise$CompletionLatch
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent method s_concurrent_impl_Promise$CompletionLatch.acquireSharedInterruptibly__I__V
[error]   called from s_concurrent_impl_Promise$DefaultPromise.tryAwait__s_concurrent_duration_Duration__Z
[error]   called from s_concurrent_impl_Promise$DefaultPromise.ready__s_concurrent_duration_Duration__s_concurrent_CanAwait__s_concurrent_impl_Promise$DefaultPromise
[error]   called from s_concurrent_impl_Promise$DefaultPromise.result__s_concurrent_duration_Duration__s_concurrent_CanAwait__O
[error]   called from s_concurrent_Await$.$$anonfun$2__p1__s_concurrent_Awaitable__s_concurrent_duration_Duration__O
[error]   called from s_concurrent_Await$.result__s_concurrent_Awaitable__s_concurrent_duration_Duration__O
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_Promise$DefaultPromise
[error]   s_concurrent_Await$
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
[error] Referring to non-existent method s_concurrent_impl_Promise$CompletionLatch.tryAcquireSharedNanos__I__J__Z
[error]   called from s_concurrent_impl_Promise$DefaultPromise.tryAwait__s_concurrent_duration_Duration__Z
[error]   called from s_concurrent_impl_Promise$DefaultPromise.ready__s_concurrent_duration_Duration__s_concurrent_CanAwait__s_concurrent_impl_Promise$DefaultPromise
[error]   called from s_concurrent_impl_Promise$DefaultPromise.result__s_concurrent_duration_Duration__s_concurrent_CanAwait__O
[error]   called from s_concurrent_Await$.$$anonfun$2__p1__s_concurrent_Awaitable__s_concurrent_duration_Duration__O
[error]   called from s_concurrent_Await$.result__s_concurrent_Awaitable__s_concurrent_duration_Duration__O
[error]   called from Lorg_scalacheck_Test$.check__Lorg_scalacheck_Test$Parameters__Lorg_scalacheck_Prop__Lorg_scalacheck_Test$Result
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__T2__T2
[error]   called from Lorg_scalacheck_Test$$anonfun$checkProperties$1.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__O
[error]   called from Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2.apply__O__Z
[error]     (already seen, not repeating call stack)
[error] involving instantiated classes:
[error]   s_concurrent_impl_Promise$DefaultPromise
[error]   s_concurrent_Await$
[error]   Lorg_scalacheck_Test$
[error]   Lorg_scalacheck_Test$$anonfun$checkProperties$1
[error]   Lorg_scalacheck_Gen$$anonfun$nonEmptyBuildableOf$2
java.lang.RuntimeException: There were linking errors
    at scala.sys.package$.error(package.scala:27)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:108)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:74)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$18.apply(ScalaJSPluginInternal.scala:243)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$18.apply(ScalaJSPluginInternal.scala:234)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (client/test:scalaJSLinkingUnitClasspath) There were linking errors
[error] Total time: 2 s, completed Feb 14, 2016 2:11:12 PM

```

**Comment by d6y** [comment]
Thank you - I'll get this fixed. Looks like a problem with using Rhino as the default JavaScript engine.  And as soon as I've got into this (should be this week), I'll get on to your awesome PR!

**Comment by d6y** [comment]
Looks like I should have upgraded ScalaCheck to "1.12.5" when I last upgraded ScalaJS.
